Change font
NIAEFEUP/sigarra-extension pull request #103
Opened 2023-07-30 17:16 UTC by toni-santos

Closes #11 

Change the website font to a something more modern and pleasing.

![image](https://github.com/NIAEFEUP/sigarra-extension/assets/72560332/eb8ddd16-d618-4cb5-83f1-c54aa2740d1c)

2023-07-30 17:27 UTC, toni-santos commented
Regarding this issue, this seems like all that we need to do. There may, as always, be bugs.

It would also be interesting to allow users to choose their own font, either from a selection made by us, available in the pop-up, or by inputting a font name, that we could then import from [Google Fonts](https://fonts.google.com), per example. Both of these features warrant some design decisions within the popup, and given the ongoing #98 PR this might not be the best of times to focus on this.

2023-08-02 20:08 UTC, thePeras commented
I think there should be an option to enable/disable this feature in the popup

2023-08-09 17:06 UTC, toni-santos commented
> I think there should be an option to enable/disable this feature in the popup.
> 
> However, I like the font a loot, it feels more comfort to read.

Just added this option and fixed a small issue on a function in the same file. Please check it out :)

2023-08-09 17:22 UTC, thePeras reviewed
Make the popup text more user friendly like "Mudar fonte de letra".

Also, now comparing to the default font, the new one seams to big. There is any possible to decrease the font-size?

2023-08-16 15:59 UTC, ttoino requested changes
Looks good, just a little comment

2023-08-16 15:59 UTC, ttoino commented on popup/components/sections/LayoutContent.js
> +                    label="Mudar font"
I agree with João, we should have a friendlier label

2023-08-16 16:02 UTC, ttoino commented
> Also, now comparing to the default font, the new one seams to big. There is any possible to decrease the font-size?

IMO it looks fine like this, but we could change the font size on the `html` element, sigarra uses `em` for its font sizes thankfully.

2023-08-16 16:33 UTC, ttoino approved these changes
Just update the branch and this should be good to merge!

2023-08-22 06:58 UTC, merged