Remake schedule page
NIAEFEUP/sigarra-extension pull request #55
Opened 2023-03-15 18:22 UTC by ttoino

Closes #54.

![image](https://user-images.githubusercontent.com/14280476/225406188-1f33acbb-7a65-41e4-b0dc-df4d4275a27a.png)

2023-06-02 19:56 UTC, thePeras requested changes
Great work guys!!

I find a little catch in classes with type O, which I don't know what it means (online?).
There is no subtitle for that type in the currently Sigarra.
The class is "O"
<img width="839" alt="Screenshot 2023-06-02 at 20 52 17" src="https://github.com/NIAEFEUP/sigarra-extension/assets/53405284/6685421b-8de0-4a65-8101-8aa8df44d6cb">

2023-06-02 19:56 UTC, thePeras commented on content-scripts/src/modules/schedule.js
> +import removeElement from "./utilities/removeElement";
```suggestion
import { lcmAll } from "./utilities/math";
```

Remove unused imports

2023-06-03 00:37 UTC, ttoino commented
> Great work guys!!
> 
> I find a little catch in classes with type O, which I don't know what it means (online?). There is no subtitle for that type in the currently Sigarra. The class is "O" <img alt="Screenshot 2023-06-02 at 20 52 17" width="839" src="https://user-images.githubusercontent.com/53405284/242979253-6685421b-8de0-4a65-8101-8aa8df44d6cb.png">

Whoops, I had never seen that class type before, nice catch! Looking at the course unit info, 'O' seems to stand for "Outra". @toni-santos which color shall we use for it? The default is gray.

2023-06-03 01:20 UTC, toni-santos commented
> > Great work guys!!
> > I find a little catch in classes with type O, which I don't know what it means (online?). There is no subtitle for that type in the currently Sigarra. The class is "O" <img alt="Screenshot 2023-06-02 at 20 52 17" width="839" src="https://user-images.githubusercontent.com/53405284/242979253-6685421b-8de0-4a65-8101-8aa8df44d6cb.png">
> 
> Whoops, I had never seen that class type before, nice catch! Looking at the course unit info, 'O' seems to stand for "Outra". @toni-santos which color shall we use for it? The default is gray.

Seeing as this type of class in particular does not fit into any of the established types of classes (Practical, Theoretic, ...) and as such lacks the same semantic meaning there isn't much in terms of color coordination that we are able to do. With this being said, I believe using grey (or similar) would be the best option as it not only keeps with the color that users already know but it also does not take away emphasis from other color combinations we already established.

2023-06-05 22:15 UTC, toni-santos commented
I have added colors for these classes, please check if it is working :)

2023-06-06 23:21 UTC, ttoino commented
> I have added colors for these classes, please check if it is working :)

The selector was missing in the code, but it's working now

2023-06-10 11:05 UTC, thePeras requested changes
It appears that O is some kind of a special case. Its content is not inside a div.

<img width="170" alt="Screenshot 2023-06-10 at 12 03 27" src="https://github.com/NIAEFEUP/sigarra-extension/assets/53405284/5425ae25-52b9-4263-95ab-cc27a274b728">
<img width="600" alt="Screenshot 2023-06-10 at 12 04 46" src="https://github.com/NIAEFEUP/sigarra-extension/assets/53405284/3a20f318-15ff-4b47-90c1-7704e8f9e690">

2023-06-10 11:32 UTC, ttoino commented
> It appears that O is some kind of a special case. Its content is not inside a div.
> 
> <img width="170" alt="Screenshot 2023-06-10 at 12 03 27" src="https://github.com/NIAEFEUP/sigarra-extension/assets/53405284/5425ae25-52b9-4263-95ab-cc27a274b728">
> <img width="600" alt="Screenshot 2023-06-10 at 12 04 46" src="https://github.com/NIAEFEUP/sigarra-extension/assets/53405284/3a20f318-15ff-4b47-90c1-7704e8f9e690">
> 

That's weird, that should have been fixed with my last commit, are you sure you pulled all the changes?

2023-06-10 14:52 UTC, thePeras commented
> That's weird, that should have been fixed with my last commit, are you sure you pulled all the changes?

Sorry, its working. 
I notice the content-script weren't beeing rebuild.

Great work!!
✅ 🛫

2023-06-10 14:53 UTC, thePeras approved these changes

2023-06-10 14:53 UTC, merged