Teacher Page
NIAEFEUP/sigarra-extension pull request #82
Opened 2023-06-12 17:47 UTC by LuisDuarte1

Closes #43 
![Screenshot 2023-06-12 at 18-47-22 FEUP - André Restivo](https://github.com/NIAEFEUP/sigarra-extension/assets/24589619/0cdfb8d5-62f4-42c9-bfa1-ec75fbb1142a)

2023-06-13 10:28 UTC, thePeras requested changes

2023-06-13 10:28 UTC, thePeras commented on content-scripts/src/modules/utilities/pageUtils.js
> +        }
You can push this to top and remove inside the ifs verification

2023-06-13 10:28 UTC, thePeras commented on content-scripts/src/modules/utilities/pageUtils.js
> +export function removeElementWithoutChildren(selector){
Can you think of a better name?

2023-06-13 10:28 UTC, thePeras commented on content-scripts/src/modules/utilities/pageUtils.js
> +    div.classList.add("keyPairTable")
Our own class name start with `se-` and follow a kebab-case convention.

2023-06-13 13:03 UTC, LuisDuarte1 commented on content-scripts/src/modules/utilities/pageUtils.js
> +    var elementList = [];
fixed sorry restivo :)

2023-06-13 14:49 UTC, thePeras commented on content-scripts/src/pages/teacher_page.js
> +        console.log(row)
remove this print

2023-06-13 14:49 UTC, thePeras commented on content-scripts/src/pages/teacher_page.js
> +        console.log(link)
Remove this print

2023-06-13 14:55 UTC, thePeras requested changes
Change divs to buttons for better acessebility

2023-06-13 15:03 UTC, ttoino commented
> Change divs to buttons for better acessebility

I think an anchor element would be more appropriate, we're just opening a new page after all

2023-06-13 15:25 UTC, toni-santos commented
> > Change divs to buttons for better acessebility
> 
> I think an anchor element would be more appropriate, we're just opening a new page after all

I agree with this, an example as to why would be the case where we attempt to open a link in a new tab with a button like Mouse-3 or Ctrl + Mouse-1, the expected behavior is for a new tab to open but currently it doesn't work, in the case of Mouse-3, or it opens in the same tab, in the case of Ctrl + Mouse-1.

Other than that this is looking great! :)

2023-06-14 08:03 UTC, LuisDuarte1 commented
You were completely right, this was written on a late night so I didn't bother then ahah, nice catch!

2023-06-14 09:40 UTC, thePeras approved these changes
Perfect!
✅ 🛫

2023-06-14 09:40 UTC, merged