Feature/class page
NIAEFEUP/sigarra-extension pull request #97
Opened 2023-07-07 15:37 UTC by toni-santos

Closes #85

2023-07-07 15:41 UTC, toni-santos commented on css/classPage.css
> +    max-height: 5000px; /* magic number for now hopefully :/ (I NEED CSS4 NOW) */
I'm using a magic number here so that we are able to get collapse/expand behavior. Should we drop this effect and just have class tables pop out?

2023-07-07 15:48 UTC, toni-santos commented
This branch has been rebased, however I'm not certain it has been done correctly please **check it out**.
Other than that and some minor styling concerns, mainly related to the close button on the dialog, it is ready for review. 👍

2023-07-18 23:20 UTC, ttoino requested changes
Nice job! It's looking good, but for some reason the expanding/collapsing functionality is not working for me on firefox.

2023-07-18 23:20 UTC, ttoino commented on content-scripts/src/modules/schedule.js
> +    const html = await fetchSigarraPage(url);
This breaks the code further down, as the `decoder` and `parser` variables are no longer in scope. An easy way to solve this is to replace the code inside the if statement with a recursive call to this same function. i.e:

```diff
  if (a) {
-     const r = await fetch(a.href);
-     const text = decoder.decode(await r.arrayBuffer());
-     html = parser.parseFromString(text, "text/html");
+     return await getClassDuration(a.href);
  }
```

2023-07-19 16:32 UTC, ttoino approved these changes

2023-07-19 16:43 UTC, merged